// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0G3CZTXhHmaOuRkcVi0tMPGo6_7DFd3s',
    appId: '1:711400058536:android:28a2c337bb43c412e39c9d',
    messagingSenderId: '711400058536',
    projectId: 'brewmate-ai',
    storageBucket: 'brewmate-ai.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNS2npn2Nay6xXaL7RODkQ44UARtQ_8cU',
    appId: '1:711400058536:web:4dea53953bafaf57e39c9d',
    messagingSenderId: '711400058536',
    projectId: 'brewmate-ai',
    storageBucket: 'brewmate-ai.firebasestorage.app',
    authDomain: 'brewmate-ai.firebaseapp.com',
    measurementId: 'G-2928F66ZS6',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjtCv2VEnZGqYwzdsD5nRsty5CUizfZ70',
    appId: '1:711400058536:ios:5f229345f8c7db80e39c9d',
    messagingSenderId: '711400058536',
    projectId: 'brewmate-ai',
    storageBucket: 'brewmate-ai.firebasestorage.app',
    androidClientId:
        '711400058536-m3mhhki5to17a0jl4rh9b953hr37vjbq.apps.googleusercontent.com',
    iosClientId:
        '711400058536-srb6o6df45fgh2raruk6qg03d7csqhcv.apps.googleusercontent.com',
    iosBundleId: 'com.brewmate.brewmateAi',
  );
}
